//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UndertaleModToolAvalonia.Assets {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UndertaleModToolAvalonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        

        public static string ThemeText {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }

        public static string LanguageText
        {
            get
            {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        public static string SystemDefaultText
        {
            get
            {
                return ResourceManager.GetString("SystemDefault", resourceCulture);
            }
        }
        public static string LightText
        {
            get
            {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        public static string DarkText
        {
            get
            {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }

        public static string LanguageChangedTitle
        {
            get
            {
                return ResourceManager.GetString("LanguageChangedTitle", resourceCulture);
            }
        }

        public static string RestartUndertaleModToolToApplyNewLanguage 
        {
            get
            {
                return ResourceManager.GetString("RestartUndertaleModToolToApplyNewLanguage", resourceCulture);
            }
        }
    }
}

